datos=["Daniel", 6, 3, 1979]
print(datos)
datos.index("Daniel")
print(datos.index("Daniel"))
datos.append("Gil")
print(datos)
datos.remove("Gil")
print(datos)
datos.extend(["otro"])
print(datos)
datos.remove("otro")
print(datos)

datos.reverse()
print(datos)
